dind1:
  extends:
    file: base-compose.yml
    service: dind

docker1:
  extends:
    file: base-compose.yml
    service: docker
  links:
  - dind1:dind1
  environment:
    DOCKER_HOST: tcp://dind1:2375

dind2:
  extends:
    file: base-compose.yml
    service: dind

docker2:
  extends:
    file: base-compose.yml
    service: docker
  links:
  - dind2:dind2
  environment:
    DOCKER_HOST: tcp://dind2:2375
