#
# Docker 1.10
#
dind10:
  image: docker:1.10-dind
  privileged: true
  restart: always
  volumes:
  - /etc/localtime:/etc/localtime:ro

docker10:
  image: eeacms/jenkins-slave-dind:1.10
  restart: always
  links:
  - dind10
  volumes:
  - /etc/localtime:/etc/localtime:ro
  environment:
  - DOCKER_HOST=tcp://dind10:2375
  - JAVA_OPTS=-Xmx2048m
  env_file:
  - .secret
  command: ["-labels", "docker docker-1.10", "-mode", "exclusive", "-name", "docker-1.10", "-retry", "10"]
