#
# Docker 1.10
#
dind10:
  image: docker:1.10-dind
  privileged: true
  restart: always
  volumes:
  - /etc/localtime:/etc/localtime:ro

docker10:
  image: eeacms/jenkins-slave-dind:1.10
  restart: always
  links:
  - dind10
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - docker10_data
  environment:
  - DOCKER_HOST=tcp://dind10:2375
  - JAVA_OPTS=-Xmx2048m
  env_file:
  - .secret
  command: ["-labels", "docker docker-1.10", "-mode", "exclusive", "-name", "docker-1.10", "-retry", "10"]

docker10_data:
  image: busybox
  volumes:
  - /var/jenkins_home/worker
  command: ["chown", "-v", "-R", "1000:1000", "/var/jenkins_home/worker"]
#
# Docker 1.9
#
dind9:
  image: docker:1.9-dind
  privileged: true
  restart: always
  volumes:
  - /etc/localtime:/etc/localtime:ro

docker9:
  image: eeacms/jenkins-slave-dind:1.9
  restart: always
  links:
  - dind9
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - docker9_data
  environment:
  - DOCKER_HOST=tcp://dind9:2375
  - JAVA_OPTS=-Xmx2048m
  env_file:
  - .secret
  command: ["-labels", "docker docker-1.9", "-mode", "exclusive", "-name", "docker-1.9", "-retry", "10"]

docker9_data:
  image: busybox
  volumes:
  - /var/jenkins_home/worker
  command: ["chown", "-v", "-R", "1000:1000", "/var/jenkins_home/worker"]
#
# Docker 1.8
#
dind8:
  image: docker:1.8-dind
  privileged: true
  restart: always
  volumes:
  - /etc/localtime:/etc/localtime:ro

docker8:
  image: eeacms/jenkins-slave-dind:1.8
  restart: always
  links:
  - dind8
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - docker8_data
  environment:
  - DOCKER_HOST=tcp://dind8:2375
  - JAVA_OPTS=-Xmx2048m
  env_file:
  - .secret
  command: ["-labels", "docker docker-1.8", "-mode", "exclusive", "-name", "docker-1.8", "-retry", "10"]

docker8_data:
  image: busybox
  volumes:
  - /var/jenkins_home/worker
  command: ["chown", "-v", "-R", "1000:1000", "/var/jenkins_home/worker"]
#
# Docker 1.7
#
dind7:
  image: docker:1.7-dind
  privileged: true
  restart: always
  volumes:
  - /etc/localtime:/etc/localtime:ro

docker7:
  image: eeacms/jenkins-slave-dind:1.7
  restart: always
  links:
  - dind7
  volumes:
  - /etc/localtime:/etc/localtime:ro
  volumes_from:
  - docker7_data
  environment:
  - DOCKER_HOST=tcp://dind7:2375
  - JAVA_OPTS=-Xmx2048m
  env_file:
  - .secret
  command: ["-labels", "docker docker-1.7", "-mode", "exclusive", "-name", "docker-1.7", "-retry", "10"]

docker7_data:
  image: busybox
  volumes:
  - /var/jenkins_home/worker
  command: ["chown", "-v", "-R", "1000:1000", "/var/jenkins_home/worker"]
